package Modelo;
// Generated Nov 17, 2017 10:26:42 AM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Equipos generated by hbm2java
 */
public class Equipos implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String descripcion;
	private Set jugadoreses = new HashSet(0);

	public Equipos() {
	}

	public Equipos(String nombre, String descripcion) {
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	public Equipos(String nombre, String descripcion, Set jugadoreses) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.jugadoreses = jugadoreses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getJugadoreses() {
		return this.jugadoreses;
	}

	public void setJugadoreses(Set jugadoreses) {
		this.jugadoreses = jugadoreses;
	}

}
