// default package
package Modelo;
// Generated Nov 17, 2017 10:26:42 AM by Hibernate Tools 5.2.6.Final

/**
 * Jugadores generated by hbm2java
 */
public class Jugadores implements java.io.Serializable {

	private Integer id;
	private Equipos equipos;
	private String nombre;
	private String apellido;
	private String posicion;

	public Jugadores() {
	}

	public Jugadores(Equipos equipos, String nombre, String apellido, String posicion) {
		this.equipos = equipos;
		this.nombre = nombre;
		this.apellido = apellido;
		this.posicion = posicion;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Equipos getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Equipos equipos) {
		this.equipos = equipos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getPosicion() {
		return this.posicion;
	}

	public void setPosicion(String posicion) {
		this.posicion = posicion;
	}

}
